# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-03 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0002_auto_20190302_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='is_walk_in',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentprofile',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentprofile',
            name='reason',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female'), (b'O', b'Other')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
