# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-02 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0002_auto_20190301_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentprofile',
            name='patient',
        ),
        migrations.AddField(
            model_name='appointmentprofile',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
