# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-02 05:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0003_auto_20190301_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentprofile',
            name='scheduled_time',
        ),
    ]
