# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-02 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0004_auto_20190302_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='scheduled_start_time',
            new_name='scheduled_start_datetime',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='scheduled_end_time',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.CharField(default=b'Not Given', max_length=1024),
        ),
    ]
