# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-02 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0005_auto_20190302_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='office',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='drchrono.Office'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointmentprofile',
            name='office',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='drchrono.Office'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.CharField(max_length=1024),
        ),
    ]
