# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-02 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0006_auto_20190302_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentprofile',
            name='office',
        ),
    ]
