# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-02 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0007_remove_appointmentprofile_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='exam_room',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='office',
            name='_exam_rooms',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
