# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-02 22:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0008_auto_20190302_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='exam_room',
            new_name='_exam_room',
        ),
    ]
