# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-04 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0010_auto_20190303_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDemographic',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('archived', models.BooleanField()),
                ('template_name', models.CharField(max_length=128)),
                ('allowed_values', models.CharField(max_length=2048)),
                ('description', models.CharField(max_length=2048)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drchrono.Doctor')),
            ],
        ),
    ]
