# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-04 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono', '0011_customdemographic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdemographic',
            name='allowed_values',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='customdemographic',
            name='archived',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='customdemographic',
            name='description',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='customdemographic',
            name='template_name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
